# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IseNinjaStack": "00_iseninja.ipynb",
         "config": "00_iseninja.ipynb",
         "ACCOUNT": "00_iseninja.ipynb",
         "ZONE_NAME": "00_iseninja.ipynb",
         "ZONE_ID": "00_iseninja.ipynb",
         "ZONE_CERT": "00_iseninja.ipynb",
         "WebsiteStack": "01_website.ipynb",
         "DevStack": "02_dev.ipynb"}

modules = ["iseninja.py",
           "website.py",
           "dev.py"]

doc_url = "https://bla15e.github.io/nb_cdk/"

git_url = "https://github.com/bla15e/nb_cdk/tree/master/"

def custom_doc_links(name): return None
